### PR TITLE
fix: Pandoc-like attributes are too restrictive

### LINKED ISSUE #62: Key-value attributes are not general enough
The syntax for attribute values in key-value pairs (`{ .... key=value }` attributes) is not general enough:

https://github.com/jgm/lunamark/blob/ae3091ad9f0e2cb3cea2571663b2c39e508bf5a7/lunamark/reader/markdown.lua#L155-L156

FWIW, Pandoc allows more things:
https://github.com/jgm/pandoc/blob/bc670665a1ce18ddc48531867b7b77c2f3493f49/src/Text/Pandoc/Readers/Markdown.hs#L658-L662

I am not reading Haskell well, but at least:
- single quoted value `key='value'`
- some escaping things
- wider range of characters (i.e. not restricted as currently to alphanums and some additions).

Found the issue while trying to have a `width="15%"` attribute pair ;)

### PR DESCRIPTION
**Pull request by Omikhleia**
Closes #62 

Carefully reading Pandoc's code, I hope I got it right now:
1. attributes `key=value` pairs
    - The key must start with a letter, followed by alphanumeric characters or `_-:.` (rather than just `_-`)
    - The value may be double-quoted _or_ single-quoted, and has less restrictions (than initially implemented)
 2. class `.class` identifiers
    - Same rule as for attribute keys
 3. hash `#id` identifiers
    - The identifier syntax was relaxed in jgm/pandoc#7920 and they are thus different (allowed _not_ to start with a letter)
 4. raw `=raw` attributes
    - They have yet another syntax, consisting in alphanums and `_-` only

### CODE REVIEW

**Comment by Witiko** [comment]
Independently implemented 1 and 2 in https://github.com/Witiko/markdown/pull/297. 3 and 4 are a good catch and I will be porting them to witiko/markdown in https://github.com/Witiko/markdown/issues/304, possibly catching some further bugs in the process. In the meantime: can you please extend the unit tests for fenced code attributes and raw attributes with some examples to prevent future regressions?

File: lunamark/reader/markdown.lua [hunk 1]
```diff
@@ -150,21 +150,30 @@ parsers.indented_blocks = function(bl)
...
+
+parsers.attrvalue   = (parsers.dquote
+                      * C((parsers.anyescaped - parsers.dquote)^0)
+                      * parsers.dquote)
+                    + (parsers.squote
+                      * C((parsers.anyescaped - parsers.squote)^0)
+                      * parsers.squote)
+                    + C((parsers.anyescaped - parsers.dquote - parsers.space - P("}"))^1)
+
+parsers.attrpair    = Cg(C((parsers.attrid)^1)
```
Comment (Witiko) [inline lunamark/reader/markdown.lua:167]: Why `(parsers.attrid)^1`? Doesn't `parsers.attrid` already handle repetition?

Comment (Omikhleia) [reply lunamark/reader/markdown.lua:167]: No idea, it was already on the previous implementation, here I just changed `parsers.identifier` to `parsers.attrid`...

Admittedly, the _previous_ code was also my contribution, but that was more than one year ago, I can't recollect the details of my thinking.

Sure, the change here doesn't make things worse, then.
Could it be made better and is the `^1` needed (if I am getting the question right), I don't know, and I'm afraid I won't have the bandwidth for investigating and testing.

Comment (Witiko) [reply lunamark/reader/markdown.lua:167]: Let's merge the following suggestion and the tests should tell us whether it's ok or not:

```suggestion
parsers.attrpair    = Cg(C(parsers.attrid)
```
